FROM golang:1.19 as builder
ENV GOPROXY=https://goproxy.cn,direct
COPY . /basego
COPY ./go.mod /basego/go.mod
COPY ./go.sum /basego/go.sum
RUN cd /basego && go build -o basego

# FROM d3fk/nfs-client:v4
FROM ubuntu:22.04
# RUN rm /bin/sh && ln -s /bin/bash /bin/sh
# RUN apt-get update
# RUN apt-get install nfs-common -y
COPY --from=builder /basego/basego /basego/basego
ENV TZ=Asia/Shanghai
RUN echo "${TZ}" > /etc/timezone \ 
&& ln -sf /usr/share/zoneinfo/${TZ} /etc/localtime \ 
&& apt update \ 
&& apt install -y tzdata \ 
&& rm -rf /var/lib/apt/lists/*

WORKDIR /basego
VOLUME [ "/basego/log","/basego/conf","/basego/tmp"]