server_port: 9606

log_config:
  log_level: INFO
  log_path: ../log/sys.log
  max_age: 10
  rotation_time: 24
  show_line: true
  is_brief: false
  json_format: false
  log_in_console: false

db_config:
  user: root
  password: 123456
  ip: 192.168.20.175
  port: 33096
  dbname: basego

tmp_file_path: ../tmp




